version: 2
references:
  base: &base
    docker:
      - image: circleci/ruby:2.6.3
        environment:
          RAILS_ENV: test
          BUNDLE_PATH: '~/bitcrowd/vendor/bundle'
    working_directory: ~/bitcrowd
jobs:
  tests:
    <<: *base
    steps:
      - checkout
      - restore_cache:
          keys:
            - bundler-cache-v1-{{ checksum "Gemfile.lock" }}
            - bundler-cache-v1-
      - run: gem install bundler
      - run:
          name: Install ruby dependencies
          command: |
            bundle check || bundle install --jobs 4 --retry 3
            bundle clean
      - run:
          name: rubocop
          command: |
            bundle exec rubocop
      - run:
          name: Database Setup
          command: |
            bundle exec rails db:create db:migrate
      - run:
          name: rake test
          command: |
            bundle exec rake test
      - save_cache:
          key: bundler-cache-v1-{{ checksum "Gemfile.lock" }}
          paths:
            - vendor/bundle

      - save_cache:
          key: repo-{{ .Environment.CIRCLE_SHA1 }}
          paths:
            - ~/bitcrowd

workflows:
  version: 2
  checks:
    jobs:
      - tests
